# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- synapse

pool:
  vmImage: ubuntu-latest

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'ME-MngEnvMCAP734805-jeanjoseph-1(b635aca8-b9cc-4989-ab6e-23d330614423)'
    ScriptType: 'InlineScript'
    Inline: 'New-AzSqlServer -ResourceGroupName "svr-dp300-labs" -Location "Central US" -ServerName "DP-300-Labs-Demo" -ComputeModel "Serverless" -SampleName "AdventureWorksLT" -Edition "GeneralPurpose" -ServerVersion "12.0"'
